# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set Python Version
        run: echo '::set-env name=PYTHON_VER::3.8.4'

      - name: Get Python Version
        run: echo 'The Python version is $PYTHON_VER'

      - name: Compile Python
        run: |
          curl -O -L https://github.com/python/cpython/archive/v$PYTHON_VER.tar.gz
          dir
          tar xvvf v$PYTHON_VER.tar.gz
          cd cpython-$PYTHON_VER
          PCbuild\build.bat -e -p ARM64 -vv --pgo        
