name: Build Python for Windows
on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/python/cpython']
        python-branch: ['3.10']
        python-arch: ['arm64']

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.10.1
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64

      - name: Clone source
        run:  |
          git clone ${{ matrix.python-remote }}
    
      - name: Compile Python
        run: |
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}

      - name: Build Python
        run: |
          mkdir pythonbuild
          python ".\cpython\PC\layout" -vv -s "." -b ".\cpython\PCBuild\arm64" -t ".\cpython\PCBuild\temp" --include-venv --copy pythonbuild

      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: cpython-${{ matrix.python-arch }}
          path: pythonbuild
