name: Build Python for Windows ARM64
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/ader1990/cpython']
        python-branch: ['win_arm64_hack']

    steps:
      - name: Compile Python
        run: |
          git clone ${{ matrix.python-remote }}
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ARM64

      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Create zip
        shell: cmd
        run: |
          mkdir cpython\PCBuild\arm64\lib
          mkdir cpython\PCBuild\arm64\include
          mkdir cpython\PCBuild\arm64\libs
          
          xcopy /i /e cpython\lib\*.* cpython\PCBuild\arm64\lib
          xcopy /i /e cpython\include\*.* cpython\PCBuild\arm64\include
          xcopy /i /e cpython\PC\pyconfig.h cpython\PCBuild\arm64\include
          xcopy /i /e cpython\PCBuild\arm64\python3.lib cpython\PCBuild\arm64\libs
          xcopy /i /e cpython\PCBuild\arm64\python39.lib cpython\PCBuild\arm64\libs
          
          powershell Compress-7Zip "cpython\PCBuild\arm64" -ArchiveFileName "cpython-arm64.zip" -Format Zip

      - uses: actions/upload-artifact@v1
        with:
          name: cpython-arm64.zip
          path: cpython-arm64.zip
