name: Build Python for Windows
on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/python/cpython']
        python-branch: ['3.10']
        python-arch: ['arm64']

    steps:
      - name: Clone source
        run:  |
          git clone ${{ matrix.python-remote }}
    
      - name: Compile Python
        run: |
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}
      
      - name: Compile Python (AMD64)
        shell: cmd
        run: |
          cd cpython
          PCbuild\build.bat -e -p x64

      - name: Build Python
        run: |
          mkdir pythonbuild
          ".\cpython\PCbuild\amd64\python.exe" PC/layout -vv -s "." -b ".\cpython\PCBuild\arm64" -t ".\cpython\PCBuild\temp" --include-venv --copy pythonbuild

      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: cpython-${{ matrix.python-arch }}
          path: pythonbuild
