name: Build Python for Windows
on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        python-remote: ['https://github.com/python/cpython']
        python-branch: ['3.10']
        python-arch: ['arm64','x64']

    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: ${{ matrix.python-branch }}.x
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64

      - name: Clone source
        uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          repository: python/cpython
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
          ref: ${{ matrix.python-branch }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: cpython
    
      - name: Compile Python
        run: |
          cd cpython
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}

      - name: Build Python
        run: |
          mkdir pythonbuild-${{ matrix.python-arch }}
          python ".\cpython\PC\layout" -vv -s ".\cpython" -b ".\cpython\PCBuild\${{ matrix.python-arch }}" -t ".\cpython\PCBuild\temp" --include-venv --copy pythonbuild-${{ matrix.python-arch }}

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: cpython-${{ matrix.python-arch }}
          path: pythonbuild-${{ matrix.python-arch }}
