name: Build Python for Windows
on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-remote: ['https://github.com/python/cpython']
        python-branch: ['3.10']
        python-arch: ['arm64']

    steps:
      - name: Compile Python
        run: |
          git clone ${{ matrix.python-remote }}
          cd cpython
          git checkout ${{ matrix.python-branch }}
          PCbuild\build.bat -e -p ${{ matrix.python-arch }}
      
      - name: Compile Python (x86)
        shell: cmd
        run: |
          cd cpython
          PCbuild\build.bat -e

      - name: Build Python
        run: |
          mkdir pythonbuild
          cpython\PCbuild\win32\python.exe PC/layout -vv -s "." -b ".\PCBuild\arm64" -t ".\PCBuild\temp" --include-venv --copy pythonbuild

      - uses: actions/upload-artifact@v1
        with:
          name: cpython-${{ matrix.python-arch }}
          path: pythonbuild
